### PR TITLE
French translation - V1

### PR DESCRIPTION
**Pull request by TBG-FR**
Here is a first version of a french `lang.yml` for TreeAssist 🥳 
I tried to do it as correct as possible, but I don't know well all features so there may be little mistakes, we'll see while using it !

By the way, I put the file in the plugin's folder and modified the config to `lang_fr` but it changed nothing... Is the jar recompilation needed to add a new language ?

### CODE REVIEW

**Comment by slipcor** [comment]
Hey, I appreciate it! Merci :D

You might need to at least reload the plugin (/treeassist reload) and maybe restart the server for this to take effect.

Oh wait I just saw in the code that I actually do not read the config setting and I always only load "lang_en.yml" - how embarrassing xD

I will push an update to fix this later today!

**Comment by TBG-FR** [comment]
You're welcome 😉 
Yeah I tried reloading and restarting, I understand why it wasn't working now 😂 Don't worry, it happens !
Thanks a lot 🙏

**Comment by slipcor** [comment]
Alright I fixed the underlying issue and will publish this build, after I pulled in your language file, I will link it on the plugin page, I hope that is okay? How can I credit you? "TBG-FR" and link to your github profile?

**Comment by TBG-FR** [comment]
Good job 💪 
Perfect for the credits !

**Pull request merged**
